@RProg.FluxoCaixa.Consolidado_HostAddress = https://localhost:7002

### Consultar consolidados por período
GET {{RProg.FluxoCaixa.Consolidado_HostAddress}}/api/consolidado?dataInicial=2024-01-01&dataFinal=2024-01-31
Accept: application/json

###

### Consultar consolidados por período com datas inválidas (para testar validação)
GET {{RProg.FluxoCaixa.Consolidado_HostAddress}}/api/consolidado?dataInicial=2024-01-31&dataFinal=2024-01-01
Accept: application/json

###

### Consultar consolidados por período e categoria específica
GET {{RProg.FluxoCaixa.Consolidado_HostAddress}}/api/consolidado/categoria/ALIMENTACAO?dataInicial=2024-01-01&dataFinal=2024-01-31
Accept: application/json

###

### Consultar consolidados por período e categoria com categoria vazia (para testar validação)
GET {{RProg.FluxoCaixa.Consolidado_HostAddress}}/api/consolidado/categoria/?dataInicial=2024-01-01&dataFinal=2024-01-31
Accept: application/json

###

### Acessar documentação Swagger
GET {{RProg.FluxoCaixa.Consolidado_HostAddress}}/
Accept: text/html

###
